export const mockOrganizationImg =
  "https://img.clerk.com/eyJ0eXBlIjoiZGVmYXVsdCIsImlpZCI6Imluc18yYzVodUx1MFo2VnYwNVN5cXM1YjNyTGhqaWUiLCJyaWQiOiJvcmdfMmNEb0V1QWFISVdYTFRaYWRvRW1lMEZNT0pTIiwiaW5pdGlhbHMiOiJEIn0";
